baseURL: https://vultr-seoul-blog.0x1306a94.com
title: 0x1306a94.com
relativeURLs: false
languageCode: zh-CN
theme: book

enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

# menu:
#   before:
#     - name: "Github"
#       url: "https://github.com/alex-shpak/hugo-book"
#       weight: 10
#     - name: "Hugo Themes"
#       url: "https://themes.gohugo.io/hugo-book/"
#       weight: 20

params:
  BookMenuBundle: /menu
  BookRepo: "https://github.com/0x1306a94/blog-content"
  BookEditPath: edit/master
  enableGitalk: true
  gitalk:
    clientID: "905de2a4c6c9a44bcf4a" # Your client ID
    clientSecret: "8364739193fb51c3067470bf9873d15a259cda5e" # Your client secret
    repo: "blog-comments" # The repo to store comments
    owner: "0x1306a94" # Your GitHub ID
    admin: "0x1306a94" # Required. Github repository owner and collaborators. (Users who having write access to this repository)
    id: "location.pathname" # The unique id of the page.
    labels: "gitalk-seoul" # Github issue labels. If you used to use Gitment, you can change it
    perPage: 15 # Pagination size, with maximum 100.
    pagerDirection: "last" # Comment sorting direction, available values are 'last' and 'first'.
    createIssueManually: false # If it is 'false', it is auto to make a Github issue when the administrators login.
    distractionFreeMode: false # Enable hot key (cmd|ctrl + enter) submit comment.
  # WechatQRCode: https://raw.githubusercontent.com/Desgard/algo/img/img/_index/wechat-qrcode.png
