name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Ready for Repo
      run: | 
        curl -XPOST -u "${{secrets.USER_NAME}}:${{secrets.PAT_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json"  -H "Content-Type: application/json" https://api.github.com/repos/${{secrets.USER_NAME}}/blog/dispatches --data '{"event_type": "repository_dispatch"}'
