name: Publish Page

on:
  repository_dispatch

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set Up Git SSL
      env:
        ACTION_DEPLOY_KEY: ${{ secrets.ACTION_DEPLOY_KEY }}
      run: |
        mkdir -p ~/.ssh/
        echo "$ACTION_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa # 配置秘钥
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts
        git config --global user.name '0x1306a94' # 换成你自己的邮箱和名字
        git config --global user.email '0x1306a94@gmail.com'
        git config --global pull.rebase false
        
    - name: Ready for Repo
      run: | 
        rake ready sys="macos"
        
    - name: Publish
      run: rake
